on:
  push:
    branches: [ main ]

jobs:
  report:
    name: Compile and upload report
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            sparse-checkout: report/
    
        - name: Compile report
          uses: vinay0410/tectonic-action@v1.1.2
          with:
            tex_path: report/report.tex
    
        - name: Upload report
          uses: actions/upload-artifact@v4
          with:
            name: report
            path: report/report.pdf
            retention-days: 14
